# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hD7lMX5QHVqlReMfoq6DkLyHY5GYUw95
"""

import requests
from bs4 import BeautifulSoup

# Target website
URL = "http://books.toscrape.com/"

# Send a request
response = requests.get(URL)
soup = BeautifulSoup(response.text, 'html.parser')

# Extract book data
def getBooks(soup):
    books = [] # Indented this line and the following lines within the function
    for item in soup.find_all('article', class_='product_pod'):
        title = item.h3.a['title']
        price = item.find('p', class_='price_color').text
        rating = item.p['class'][1] # e.g., 'One', 'Two', etc.
        books.append({
            'title': title,
            'price': price,
            'rating': rating
        })
    return books # Indented this line as well

# Call the function and print results
# Call the function and print results
books = getBooks(soup)
for book in books:
    print(f"Title: {book['title']}\nPrice: {book['price']}\nRating: {book['rating']}\n")



